"""Generate standalone, runnable Playwright test files from compiled actions.

Unlike the pytest-bdd stubs (skeletons to fill in), this emits complete
executable tests — the full path from requirement to green run.
"""

import re


def _test_name(name):
    n = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")[:60].rstrip("_")
    return f"test_{n or 'scenario'}"


def _render_action(a, base_url, indent="    "):
    if a.type == "goto":
        url = a.url if a.url.startswith("http") else base_url + a.url
        return f'{indent}page.goto("{url}")  # {a.description}'
    if a.type == "fill":
        return (f'{indent}page.fill("{a.selector}", "{a.value}")'
                f"  # {a.description}")
    if a.type == "click":
        return f'{indent}page.click("{a.selector}")  # {a.description}'
    if a.type == "expect_url":
        return (f'{indent}expect(page).to_have_url(re.compile(r".*{re.escape(a.url)}$"))'
                f"  # {a.description}")
    if a.type == "expect_visible":
        return (f'{indent}expect(page.locator("{a.selector}")).to_be_visible()'
                f"  # {a.description}")
    if a.type == "expect_text":
        return (f'{indent}expect(page.locator("{a.selector}")).to_contain_text("{a.text}")'
                f"  # {a.description}")
    return f"{indent}# unsupported action: {a.type}"


def generate_playwright(compiled, target, feature_title="feature") -> str:
    """Render compiled scenarios as one runnable Playwright module."""
    base_url = target["base_url"]
    lines = [
        f'"""Executable Playwright tests generated from "{feature_title}".',
        "",
        "Generated by ai-gherkin-generator. Run:  pytest test_generated.py",
        '"""',
        "import re",
        "",
        "from playwright.sync_api import expect, sync_playwright",
        "",
        "",
        "def _browser():",
        "    pw = sync_playwright().start()",
        "    browser = pw.chromium.launch()",
        "    return pw, browser",
        "",
        "",
    ]
    runnable = [c for c in compiled if not c.skipped]
    for cs in runnable:
        lines.append(f"def {_test_name(cs.name)}():")
        lines.append('    pw, browser = _browser()')
        lines.append("    page = browser.new_page()")
        lines.append("    try:")
        for a in cs.actions:
            lines.append(_render_action(a, base_url, indent="        "))
        lines.append("    finally:")
        lines.append("        browser.close()")
        lines.append("        pw.stop()")
        lines.append("")
        lines.append("")
    skipped = [c for c in compiled if c.skipped]
    if skipped:
        lines.append("# Skipped (no compilable browser actions for the target app):")
        for cs in skipped:
            lines.append(f"#   - {cs.name}: {cs.skipped}")
    header = f"# {len(runnable)} runnable / {len(compiled)} scenarios compiled from '{feature_title}'\n"
    return header + "\n".join(lines).rstrip() + "\n"
